markdown: kramdown
permalink: /blog/:year/:title/
relative_permalinks: true
exclude:
  - CNAME
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - node_modules/
  - package.json
  - Rakefile
  - README.md
  - vendor/

layouts: ./_noita

noita:
  name: VA3CGR.NET
  description: Ham site by VA3CGR
  author:
    name: Cees de Groot
    url: http://evrl.com/
  lang: en
  favicons:
    - /assets/2014/04/21/favicon-152.png
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      - name: Blog
        url: /blog/

compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
